#服务器端口号
server:
  port: 9001
spring:
  application:
  #指定服务名
    name: tensquare-base
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: Worm
    password: 41440092wei
  #JPA的整合配置
  jpa:
    database: mysql
    show-sql: true